### ISSUE TITLE
Missing epochs in ZTF20acrinvz

### ISSUE THREAD

**Issue by erezimm** [fritz-marshal/fritz-beta-feedback#48] opened 2020-11-19 12:02 UTC
Looking at the lightcurves of ZTF20acrinvz in both the Growth Marshal and in Fritz I see an extra observation in g band in the growth marshal that does not show up in the fritz
![image](https://user-images.githubusercontent.com/53300818/99664035-36430e00-2a70-11eb-8130-b82ec6c849d7.png)
vs
![image](https://user-images.githubusercontent.com/53300818/99664061-3fcc7600-2a70-11eb-8aa1-c551a9b0a0f3.png)

**Comment by dannygoldstein** [comment] 2020-11-19 22:00
Will be addressed by https://github.com/skyportal/skyportal/issues/1368

**Comment by dannygoldstein** [comment] 2020-11-19 22:03
Actually, that issue already cover this use case. Closing as a duplicate of  https://github.com/skyportal/skyportal/issues/1368 - when that issue is addressed it will fix this one.

**Closed as completed by dannygoldstein** 2020-11-19 22:03 UTC
Labels: bug, duplicate
