### ISSUE TITLE
observing run keeps loading

### ISSUE THREAD

**Issue by igorandreoni** [fritz-marshal/fritz-beta-feedback#44] opened 2020-11-18 21:28 UTC
Please fill out relevant sections below; remove those that are unused.

**Describe the bug**
At least three users cannot display the observing run https://fritz.science/run/2

**To Reproduce**
1. Go to 'https://fritz.science/run/2'
2. Error appears for a few seconds "Object of type MaskedConstant is not JSON serializable"

**Expected behavior**
Open the observing run page

**Screenshots**
![Screen Shot 2020-11-18 at 1 10 54 PM](https://user-images.githubusercontent.com/22763282/99590087-be0e1700-29a1-11eb-81c1-9041c79f5058.png)

**Platform information:**
 - Fritz version:  v0.9.dev0+git20201117.9e4dd70
 - Browser: Safari
   - [x ] I'm browsing on a desktop
   - [ ] I'm browsing on my phone

**Additional context**
We are observing tomorrow, so it would be great to have this solved asap. Thanks.

**Comment by dannygoldstein** [comment] 2020-11-18 21:43
Needed to join CLU-caltech to reproduce

**Comment by dannygoldstein** [comment] 2020-11-18 22:18
This is happening because ZTF20acgrjqm, which is saved to CLU-caltech, is assigned to the run, and that object is not up (up defined as airmass < 2) during the run. This causes 
```
WARNING: TargetNeverUpWarning: Target with index 23 does not cross horizon=30.0 deg within 24 hours [astroplan.observer]
```
to be thrown, making the rise/set times of this object a  MaskedConstant, which doesn't know how to be serialized and sent to the frontend. Will push a fix...

**Comment by dannygoldstein** [comment] 2020-11-18 22:19
For an immediate fix, un assign this target from the run for now.

**Closed as completed** 2020-11-24 21:28 UTC
Labels: bug, triage: high priority
