### ISSUE TITLE
Group page

### ISSUE THREAD

**Issue by steveschulze** [fritz-marshal/fritz-beta-feedback#19] opened 2020-10-28 08:08 UTC
Hi,

And a few comments on the group page.

**Critical**
-User names should be real names, not acronyms or pseudonyms
-Name list has to be alphabetically sorted
-We need an option to add a batch of users at ones.

Cheers,

Steve

**Comment by dannygoldstein** [comment] 2020-11-02 21:55
@steveschulze, in future please file each of these as a separate issue. makes it easier for us to track 

> -User names should be real names, not acronyms or pseudonyms

Closing this as a wontfix, usernames are specifically designed to be configurable unique tokens for identifying a user account. cc @profjsb 


> Name list has to be alphabetically sorted

Duplicate of #15

> We need an option to add a batch of users at ones.

Already implemented in https://github.com/skyportal/skyportal/pull/1125

**Closed as completed by dannygoldstein** 2020-11-02 21:55 UTC
