### ISSUE TITLE
No way to download spectra from fritz

### ISSUE THREAD

**Issue by idoirani** [fritz-marshal/fritz-beta-feedback#64] opened 2020-11-29 11:52 UTC
Hello, 

There is currently no way to download spectra from fritz as ascii/FITS files. It would be good to add this, in addition to ways to view the header. 

Thanks, 
Ido

**Comment by dannygoldstein** [comment] 2020-11-29 18:52
duplicate of #30

**Closed as completed by dannygoldstein** 2020-11-29 18:52 UTC
Labels: duplicate, enhancement
