### ISSUE TITLE
Consistent colors for r band and g band in the scanning page

### ISSUE THREAD

**Issue by erezimm** [fritz-marshal/fritz-beta-feedback#57] opened 2020-11-25 13:39 UTC
I noticed that in the scanning page if i band exists for a lightcurve then the r band  marker in the lightcurve turns red while i band is orange unlike the case where there have been no i band observations.
It would be nice if r band would always have a red marker, i band a yellow marker and g band a green marker like in the GROWTH marshal.
Thanks!
![image](https://user-images.githubusercontent.com/53300818/100234872-5cffb980-2f34-11eb-9336-331a60da0ac1.png)

**Comment by dmitryduev** [comment] 2020-11-26 07:48
@stefanv https://github.com/vega/vega-lite/issues/6708 is still an open issue...

**Comment by stefanv** [comment] 2020-12-03 02:09
Duplicate of https://github.com/skyportal/skyportal/issues/681

**Comment by guynir42** [comment] 2022-03-29 20:20
Closed as it is a duplicate of SP #681

**Closed as completed by guynir42** 2022-03-29 20:20 UTC
Labels: duplicate, enhancement, triage: low priority
