### ISSUE TITLE
[Request] Upload Spectroscopy & Spectrum Toolbar

### ISSUE THREAD

**Issue by AndyTza** [fritz-marshal/fritz-beta-feedback#22] opened 2020-10-30 02:11 UTC
Hi all, 

I just have a few minor recommendations for the manual upload spectroscopy and the spectrum toolbar.

- Can the observers & reducers list be sorted alphabetically? This can be quite hard to find one user when some filters have many users associated

- **Observation MJD**, can this be converted to MM/DD/YR format?

- Spectrum lines tabs, redshift, and V_expansion are currently not working

- Can we include a binning factor to the spectra displayed on the source page? This can be particularly useful to increase/decrease the spectrum resolution

Thanks! 🔭

**Comment by dannygoldstein** [comment] 2020-11-02 21:51
@atzanidakis In future, can you please file each of these as an individual issue. Makes it easier to keep track of things 

> Can the observers & reducers list be sorted alphabetically? This can be quite hard to find one user when some filters have many users associated

Duplicate of  #15

> Observation MJD, can this be converted to MM/DD/YR format?

No as this results in a loss of precision in the stored date of the spectrum. We need sub-second precision on the shutter times. 

> Spectrum lines tabs, redshift, and V_expansion are currently not working

This is a known issue. We are working on it in https://github.com/skyportal/skyportal/issues/1247

> Can we include a binning factor to the spectra displayed on the source page? This can be particularly useful to increase/decrease the spectrum resolution

Tracked in https://github.com/skyportal/skyportal/issues/10

**Closed as completed by dannygoldstein** 2020-11-02 21:51 UTC
