### ISSUE TITLE
Light curve not loading on source page

### ISSUE THREAD

**Issue by tawnysit** [fritz-marshal/fritz-beta-feedback#108] opened 2021-07-19 20:48 UTC
**Describe the bug**
The light curve on the source page does not load for some sources, and where the photometry plot should be are just the words "Loading Plotting Data..."
A red error/warning that reads "Out of range float values are not JSON compliant" also shows up in the upper right hand corner of the page when this happens.
However, an alert had been triggered since the source showed up on the candidates page.

**To Reproduce**
Open the source page for [ZTF21abmlahy](https://fritz.science/source/ZTF21abmlahy).

**Expected behavior**
See the light curve of the source in the Photometry section of the page.

**Screenshots**
![no light curve on source page bug](https://user-images.githubusercontent.com/33436709/126216231-34afa6e3-f051-4f07-bc4a-033111971fa3.PNG)

**Platform information:**
 - Fritz version:  v0.9.dev0+git20210714.abfba89+fritz.3a93786
 - Browser
   - [x] I'm browsing on a desktop
   - [ ] I'm browsing on my phone

**Additional context**
I've tried loading the page on both Google Chrome and Microsoft Edge, and refreshed at different times throughout a day (including ctrl+F5 hard refreshes) -  none of these methods loaded the light curve.

**Comment by dmitryduev** [comment] 2021-07-19 21:32
Thanks for the report, @tawnysit! 

In this particular case, you saw this behavior because your account was missing access to Partnership data (programid=2), but had access to Public and Caltech data. I granted that, so you should not be seeing that anymore.

Closing this in favor of https://github.com/fritz-marshal/fritz/issues/319 where the issue is discussed in a bit more detail.

**Closed as completed by dmitryduev** 2021-07-19 21:32 UTC
Labels: bug
