### ISSUE TITLE
Crosshair misalignment when target not centered in ZTF cutout

### ISSUE THREAD

**Issue by scizen9** [fritz-marshal/fritz-beta-feedback#90] opened 2021-03-17 19:11 UTC
**Describe the bug**
When the target is not centered in the ZTF cutout, the crosshair is mis-aligned

**To Reproduce**
 Go to https://fritz.science/source/ZTF21aamqgid
Examine cutouts.

**Expected behavior**
Regardless of target placement in ZTF cutout, the crosshair should be centered on the target.

**Screenshots**

![image](https://user-images.githubusercontent.com/6845428/111524292-7910ac00-8719-11eb-9b9e-11e4aaef8b10.png)

**Platform information:**
 - Fritz version: 
![image](https://user-images.githubusercontent.com/6845428/111524518-c0973800-8719-11eb-83f1-d2317a5729a1.png)

 - Browser
   - [ x] I'm browsing on a desktop
   - [ ] I'm browsing on my phone

**Comment by dmitryduev** [comment] 2021-03-17 19:14
Duplicate of https://github.com/dmitryduev/kowalski/issues/82, so closing.

**Closed as completed by dmitryduev** 2021-03-17 19:14 UTC
Labels: bug
