### ISSUE TITLE
i-band photometry not visible on Source page

### ISSUE THREAD

**Issue by joeljoh** [fritz-marshal/fritz-beta-feedback#69] opened 2020-11-30 20:53 UTC
**Describe the bug**
I-band photometry for some objects is not shown on the source page.
When saving e.g. ZTF20abfadbm, gri photometry is shown on the Alerts page but not on the source page.

**To Reproduce**
1. Go to Alerts page: https://fritz.science/alerts/ztf/ZTF20aawabry
2. Go to Source page: https://fritz.science/source/ZTF20aawabry
3. See no i-band

**Screenshots**
<img width="1365" alt="Screenshot 2020-11-30 at 19 28 05" src="https://user-images.githubusercontent.com/71870267/100662831-b82b1500-3355-11eb-9a7b-931f8477707e.png">
<img width="1018" alt="Screenshot 2020-11-30 at 19 28 21" src="https://user-images.githubusercontent.com/71870267/100662843-bb260580-3355-11eb-8076-c3f5f620aff9.png">

**Platform information:**
 - Fritz version:  (find this in the [About](https://fritz.science/about) page)
 - Browser Chrome on Mac OS X

**Comment by dannygoldstein** [comment] 2020-11-30 20:55
Duplicate of #28, will be fixed by https://github.com/skyportal/skyportal/issues/1368

**Closed as completed by dannygoldstein** 2020-11-30 20:55 UTC
Labels: bug, duplicate
