### ISSUE TITLE
Sources not appearing in source search-box

### ISSUE THREAD

**Issue by joeljoh** [fritz-marshal/fritz-beta-feedback#42] opened 2020-11-17 19:53 UTC
It seems like some sources do not appear in the search box if they have been saved from the alerts page. Unclear if this is due to the source being saved without selecting a group or belonging to a group to which I don't have permissions.

<img width="1121" alt="Screenshot 2020-11-17 at 10 27 21" src="https://user-images.githubusercontent.com/71870267/99439539-970a0380-2915-11eb-9685-233709fe62b5.png">

**Comment by stefanv** [comment] 2020-11-17 20:00
Thanks for the report @joeljoh.  My first guess would be that we match strings starting from the beginning; will investigate.

**Comment by stefanv** [comment] 2020-11-17 20:00
Does not seem to be an issue with matching in the middle of string.

**Comment by joeljoh** [comment] 2020-11-17 20:13
Ah, I was actually not trying to do that (the "ZTF20.." is just outside the box). Perhaps a poor example, since this object is now searchable. A current example (for me at least) is ZTF20acqoiyt: Saved source, but not indexed on sources page nor in the search field.

<img width="1428" alt="Screenshot 2020-11-17 at 21 08 54" src="https://user-images.githubusercontent.com/71870267/99442412-a1c69780-2919-11eb-8c15-3ab59d238253.png">
<img width="1405" alt="Screenshot 2020-11-17 at 21 09 10" src="https://user-images.githubusercontent.com/71870267/99442417-a4c18800-2919-11eb-8235-04ec16080d27.png">
<img width="1415" alt="Screenshot 2020-11-17 at 21 09 25" src="https://user-images.githubusercontent.com/71870267/99442422-a5f2b500-2919-11eb-9719-a1578d9b637d.png">

**Comment by stefanv** [comment] 2020-11-17 20:16
Thanks, @joeljoh, this is very helpful feedback, since I can now see that the problem perhaps is with filtering in general (these two features share some functionality).  The first screenshot is surprising, because there the two searches yielded different results.

@acrellin, I wonder if you have any insight into what might be happening here?

**Comment by acrellin** [comment] 2020-11-17 20:20
Yes, that source is not saved to any groups that @joeljoh has access to, so by design will not show up in the source search results. Different logic (whether at least one photometry data point associated with the source should be viewable by the user) determines access to the source page. So the question is whether those two access control methods should be unified across different avenues of accessing source data.

**Comment by acrellin** [comment] 2020-11-17 20:20
cc @dannygoldstein

**Comment by stefanv** [comment] 2020-11-17 20:31
My gut feeling is that the most permissive source discovery mechanism should be used everywhere.

**Comment by acrellin** [comment] 2020-11-17 20:32
I agree. @dannygoldstein ?

**Comment by dannygoldstein** [comment] 2020-11-17 22:02
Yep, I agree,

**Comment by stefanv** [comment] 2020-12-03 02:12
Closed by https://github.com/skyportal/skyportal/pull/1374

**Comment by dannygoldstein** [comment] 2020-12-03 02:14
Still open, will be closed by skyportal/skyportal#1307

**Comment by dmitryduev** [comment] 2021-04-20 18:53
Fixed and deployed, closing.

**Closed as completed by dmitryduev** 2021-04-20 18:53 UTC
Labels: bug
