### ISSUE TITLE
Possible Bug with Centroid Plot 

### ISSUE THREAD

**Issue by AndyTza** [fritz-marshal/fritz-beta-feedback#32] opened 2020-11-13 18:35 UTC
It appears that the centroid plot for each source is not entirely accurate. For most sources, the **offset** estimates are always ~0 when in fact if you look at the science images there's clearly a pretty obvious offset from the host nucleus.

<img width="408" alt="Screen Shot 2020-11-13 at 1 29 54 PM" src="https://user-images.githubusercontent.com/22720676/99107967-a35c2c80-25b4-11eb-8d9f-46d4adb6d660.png"> 
Right now, it looks like the centroid is being calculated from the alerts alone, ideally, this would need to be done with respect to the host coordinate.

**Comment by dannygoldstein** [comment] 2020-11-13 18:36
Duplicate of https://github.com/skyportal/skyportal/issues/1011

**Closed as completed by dannygoldstein** 2020-11-13 18:36 UTC
Labels: duplicate
